[libraries]
asm = { module = "org.ow2.asm:asm", version = "9.5" }

[plugins]
gradle-publish-plugin = { id = "com.gradle.plugin-publish", version = "1.1.0" }
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
