[libraries]
asm = { module = "org.ow2.asm:asm", version = "9.6" }

[plugins]
gradle-publish-plugin = { id = "com.gradle.plugin-publish", version = "1.2.1" }
spotless = { id = "com.diffplug.spotless", version = "6.23.1" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
