[libraries]
asm = { module = "org.ow2.asm:asm", version = "9.7.1" }

[plugins]
gradle-publish-plugin = { id = "com.gradle.plugin-publish", version = "1.3.1" }
spotless = { id = "com.diffplug.spotless", version = "7.0.2" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
