[libraries]
asm = { module = "org.ow2.asm:asm", version = "9.7" }

[plugins]
gradle-publish-plugin = { id = "com.gradle.plugin-publish", version = "1.3.0" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
