[libraries]
asm = { module = "org.ow2.asm:asm", version = "9.4" }

[plugins]
gradle-publish-plugin = { id = "com.gradle.plugin-publish", version = "1.1.0" }
spotless = { id = "com.diffplug.spotless", version = "6.16.0" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.2.0" }
