# Copyright (C) 2021 The Authors of projectnessie
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  java:
    name: Java/Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: gradle-build-plugins

      # Setup Gradle properties, heap requirements are for the "Integration test w/ Nessie".
      - name: Setup gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8" >> ~/.gradle/gradle.properties
          echo "org.gradle.vfs.watch=false" >> ~/.gradle/gradle.properties

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: gradle-build-plugins
          arguments: assemble check publishToMavenLocal

      - name: Clone Nessie for integration test
        uses: actions/checkout@v3
        with:
          repository: projectnessie/nessie
          ref: main
          path: nessie

      # Build Nessie as an integration test.
      # Use :servers:quarkus-cli:intTest as a canary, because that integration uses the Quarkus plugin.
      - name: Integration test w/ Nessie
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: nessie
          arguments: --include-build ../gradle-build-plugins jar testClasses publishToMavenLocal :servers:quarkus-cli:intTest
